FROM tiangolo/meinheld-gunicorn-flask:python3.7
#
# Install requirements early so we can change code and re-build quickly
COPY requirements-prod.txt requirements.txt
RUN  pip install --no-cache-dir -r requirements.txt

ARG module
ARG package

ADD ./${module} /app/${module}
WORKDIR /app
COPY local.ini local.ini
COPY docker.ini overrides.ini

ENV DEMO=docker-demo
ENV LOG_LEVEL=info
 
ENV MODULE_NAME="$module.$package.__main__"
ENV VARIABLE_NAME="app"
ENV WEB_CONCURRENCY=1
ENV HOST=0.0.0.0
ENV PORT=5000
